pkgname=ownCloud

post_install() {
   echo "Add the following lines into /etc/httpd/conf/httpd.conf:"
   echo "Include /etc/httpd/conf/extra/owncloud.conf"
   echo "LoadModule php5_module modules/libphp5.so"
   echo "Include conf/extra/php5_module.conf"
   echo
   echo "Uncomment extensions gd.so intl.so iconv.so openssl.so xmlrpc.so"
   echo "zip.so and either pdo_sqlite.so sqlite3.so (for the SQLite backend)"
   echo "or mysqli.so pdo_mysql.so (for the MySQL backend) in /etc/php/php.ini"
}
